#!/bin/sh

set -e

MIME_BOUNDARY="$1"
# extract-pst will replace `FILENAME",` with end of filename and entire contentType
JSON_TEMPLATE="$(echo "$2" | jq '{ filename: (.filename + "FILENAME"), languageCode: .languageCode, wantOcr: .wantOcr, wantSplitByPage: .wantSplitByPage, metadata: .metadata }')"

cat > input.blob
exec /app/extract-pst "$MIME_BOUNDARY" "$JSON_TEMPLATE"
